# Form implementation generated from reading ui file 'e:\gzq\Tool\Admin\2025\CraftHub\tool\menuTool\timestampTool\ui\timestamp.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TimestampTranser(object):
    def setupUi(self, TimestampTranser):
        TimestampTranser.setObjectName("TimestampTranser")
        TimestampTranser.resize(950, 530)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=TimestampTranser)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 891, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gridLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit_src = QtWidgets.QPlainTextEdit(parent=self.gridLayoutWidget)
        self.plainTextEdit_src.setStyleSheet("            QPlainTextEdit {\n"
"                background-color: lightgray;\n"
"                color: black;\n"
"            }")
        self.plainTextEdit_src.setObjectName("plainTextEdit_src")
        self.horizontalLayout.addWidget(self.plainTextEdit_src)
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.plainTextEdit_dst = QtWidgets.QPlainTextEdit(parent=self.gridLayoutWidget)
        self.plainTextEdit_dst.setStyleSheet("            QPlainTextEdit {\n"
"                background-color: lightgray;\n"
"                color: black;\n"
"            }")
        self.plainTextEdit_dst.setObjectName("plainTextEdit_dst")
        self.horizontalLayout.addWidget(self.plainTextEdit_dst)

        self.retranslateUi(TimestampTranser)
        self.pushButton.clicked.connect(TimestampTranser._trans) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TimestampTranser)

    def retranslateUi(self, TimestampTranser):
        _translate = QtCore.QCoreApplication.translate
        TimestampTranser.setWindowTitle(_translate("TimestampTranser", "Form"))
        self.pushButton.setText(_translate("TimestampTranser", "trans\n"
"-->"))
