# Form implementation generated from reading ui file 'e:\gzq\Tool\Admin\2025\CraftHub\tool\menuTool\tftpTool\ui\tftpDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(537, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 70, 471, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font-style:italic;\n"
"font-weight: bold;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setStyleSheet("font-style:italic;\n"
"font-weight: bold;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font-style:italic;\n"
"font-weight: bold;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_rootDir = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.comboBox_rootDir.setObjectName("comboBox_rootDir")
        self.gridLayout.addWidget(self.comboBox_rootDir, 2, 1, 1, 2)
        self.pushButton_browse = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.gridLayout.addWidget(self.pushButton_browse, 2, 3, 1, 1)
        self.comboBox_port = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.comboBox_port.setObjectName("comboBox_port")
        self.gridLayout.addWidget(self.comboBox_port, 1, 1, 1, 3)
        self.comboBox_ip = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.comboBox_ip.setObjectName("comboBox_ip")
        self.gridLayout.addWidget(self.comboBox_ip, 0, 1, 1, 3)
        self.pushButton_init = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_init.sizePolicy().hasHeightForWidth())
        self.pushButton_init.setSizePolicy(sizePolicy)
        self.pushButton_init.setObjectName("pushButton_init")
        self.gridLayout.addWidget(self.pushButton_init, 3, 3, 1, 1)
        self.pushButton_command = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_command.setObjectName("pushButton_command")
        self.gridLayout.addWidget(self.pushButton_command, 3, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ip "))
        self.label_3.setText(_translate("Dialog", "rootDir "))
        self.label_2.setText(_translate("Dialog", "port "))
        self.pushButton_browse.setText(_translate("Dialog", "Browse"))
        self.pushButton_init.setText(_translate("Dialog", "init"))
        self.pushButton_command.setText(_translate("Dialog", "command"))
