# Form implementation generated from reading ui file 'e:\gzq\Tool\CraftHub\CraftHub\ui\surveyMaster\input.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(950, 400)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 871, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_slider = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame_slider.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_slider.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_slider.setObjectName("frame_slider")
        self.label = QtWidgets.QLabel(parent=self.frame_slider)
        self.label.setGeometry(QtCore.QRect(250, 55, 321, 111))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame_slider)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "这是输入界面"))
