# Form implementation generated from reading ui file 'd:\Tool\CraftHub\ui\imageSplit\imageSplit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(912, 440)
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setGeometry(QtCore.QRect(60, 30, 801, 381))
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 300))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 400))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 400))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 10, 721, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_selectSrc = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_selectSrc.setObjectName("pushButton_selectSrc")
        self.gridLayout.addWidget(self.pushButton_selectSrc, 1, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.comboBox_substationCount = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.comboBox_substationCount.setObjectName("comboBox_substationCount")
        self.gridLayout.addWidget(self.comboBox_substationCount, 4, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=self.gridLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 521, 158))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_sta = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_sta.setStyleSheet("\n"
"QLabel {\n"
"    color: #000000;\n"
"    font-style: italic;\n"
"    font-weight: 500;\n"
"    font-size: 12px;\n"
"    font-family: \'Segoe UI\', \'Microsoft YaHei\', sans-serif;\n"
"    border-radius: 3px;\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.label_sta.setText("")
        self.label_sta.setObjectName("label_sta")
        self.gridLayout_2.addWidget(self.label_sta, 0, 1, 1, 1)
        self.label_room = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_room.setStyleSheet("QLabel {\n"
"    color: #000000;\n"
"    font-style: italic;\n"
"    font-weight: 500;\n"
"    font-size: 12px;\n"
"    font-family: \'Segoe UI\', \'Microsoft YaHei\', sans-serif;\n"
"    border-radius: 3px;\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.label_room.setText("")
        self.label_room.setObjectName("label_room")
        self.gridLayout_2.addWidget(self.label_room, 2, 1, 1, 1)
        self.label_cabinet = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_cabinet.setStyleSheet("QLabel {\n"
"    color: #000000;\n"
"    font-style: italic;\n"
"    font-weight: 500;\n"
"    font-size: 12px;\n"
"    font-family: \'Segoe UI\', \'Microsoft YaHei\', sans-serif;\n"
"    border-radius: 3px;\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.label_cabinet.setText("")
        self.label_cabinet.setObjectName("label_cabinet")
        self.gridLayout_2.addWidget(self.label_cabinet, 4, 1, 1, 1)
        self.progressBar_sta = QtWidgets.QProgressBar(parent=self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_sta.sizePolicy().hasHeightForWidth())
        self.progressBar_sta.setSizePolicy(sizePolicy)
        self.progressBar_sta.setStyleSheet("QProgressBar {\n"
"                border-radius: 5px;\n"
"                background-color: #E3F2FD;\n"
"                text-align: center;\n"
"                font-weight: bold;\n"
"                color: #1565C0;\n"
"            }")
        self.progressBar_sta.setMaximum(103)
        self.progressBar_sta.setProperty("value", 0)
        self.progressBar_sta.setTextVisible(True)
        self.progressBar_sta.setInvertedAppearance(False)
        self.progressBar_sta.setObjectName("progressBar_sta")
        self.gridLayout_2.addWidget(self.progressBar_sta, 1, 1, 1, 1)
        self.progressBar_room = QtWidgets.QProgressBar(parent=self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_room.sizePolicy().hasHeightForWidth())
        self.progressBar_room.setSizePolicy(sizePolicy)
        self.progressBar_room.setStyleSheet("QProgressBar {\n"
"                border-radius: 5px;\n"
"                background-color: #E3F2FD;\n"
"                text-align: center;\n"
"                font-weight: bold;\n"
"                color: #1565C0;\n"
"            }")
        self.progressBar_room.setProperty("value", 0)
        self.progressBar_room.setTextVisible(True)
        self.progressBar_room.setInvertedAppearance(False)
        self.progressBar_room.setObjectName("progressBar_room")
        self.gridLayout_2.addWidget(self.progressBar_room, 3, 1, 1, 1)
        self.progressBar_cabinet = QtWidgets.QProgressBar(parent=self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_cabinet.sizePolicy().hasHeightForWidth())
        self.progressBar_cabinet.setSizePolicy(sizePolicy)
        self.progressBar_cabinet.setStyleSheet("QProgressBar {\n"
"                border-radius: 5px;\n"
"                background-color: #E3F2FD;\n"
"                text-align: center;\n"
"                font-weight: bold;\n"
"                color: #1565C0;\n"
"            }")
        self.progressBar_cabinet.setProperty("value", 0)
        self.progressBar_cabinet.setTextVisible(True)
        self.progressBar_cabinet.setInvertedAppearance(False)
        self.progressBar_cabinet.setObjectName("progressBar_cabinet")
        self.gridLayout_2.addWidget(self.progressBar_cabinet, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 7, 0, 2, 2)
        self.comboBox_splitMod = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.comboBox_splitMod.setObjectName("comboBox_splitMod")
        self.gridLayout.addWidget(self.comboBox_splitMod, 3, 1, 1, 1)
        self.lineEdit_src = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_src.setObjectName("lineEdit_src")
        self.gridLayout.addWidget(self.lineEdit_src, 1, 1, 1, 1)
        self.pushButton_openSrc = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_openSrc.setObjectName("pushButton_openSrc")
        self.gridLayout.addWidget(self.pushButton_openSrc, 1, 3, 1, 1)
        self.lineEdit_dst = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_dst.setObjectName("lineEdit_dst")
        self.gridLayout.addWidget(self.lineEdit_dst, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.pushButton_openDst = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_openDst.setObjectName("pushButton_openDst")
        self.gridLayout.addWidget(self.pushButton_openDst, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.pushButton_selectOutput = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_selectOutput.setObjectName("pushButton_selectOutput")
        self.gridLayout.addWidget(self.pushButton_selectOutput, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.pushButton_trans = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_trans.setObjectName("pushButton_trans")
        self.gridLayout.addWidget(self.pushButton_trans, 7, 2, 2, 1)
        self.pushButton_clear = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 7, 3, 2, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        self.pushButton_clear.clicked.connect(Form._clear) # type: ignore
        self.pushButton.clicked.connect(Form._set) # type: ignore
        self.pushButton_trans.clicked.connect(Form._trans) # type: ignore
        self.pushButton_openSrc.clicked.connect(Form._openSrc) # type: ignore
        self.pushButton_selectOutput.clicked.connect(Form._selectOutput) # type: ignore
        self.comboBox_splitMod.currentTextChanged['QString'].connect(Form._updateSubstationCount) # type: ignore
        self.pushButton_selectSrc.clicked.connect(Form._selectSrc) # type: ignore
        self.pushButton_openDst.clicked.connect(Form._openDst) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_selectSrc.setText(_translate("Form", "..."))
        self.pushButton.setText(_translate("Form", "设置"))
        self.groupBox.setTitle(_translate("Form", "状态栏"))
        self.pushButton_openSrc.setText(_translate("Form", "OPEN"))
        self.label_6.setText(_translate("Form", "变电站数量"))
        self.label_7.setText(_translate("Form", "分割模式"))
        self.pushButton_openDst.setText(_translate("Form", "OPEN"))
        self.label.setText(_translate("Form", "图片文件夹"))
        self.pushButton_selectOutput.setText(_translate("Form", "..."))
        self.label_2.setText(_translate("Form", "输出文件夹"))
        self.pushButton_trans.setText(_translate("Form", "Trans"))
        self.pushButton_clear.setText(_translate("Form", "clear"))
