# Form implementation generated from reading ui file 'e:\gzq\Tool\CraftHub\CraftHub\ui\home\home.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(933, 500)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 20, 821, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("            QLabel {\n"
"                font-size: 9px;       /* 字体大小 */\n"
"                font-weight: bold;     /* 粗体 */\n"
"                padding: 10px;         /* 内边距 */\n"
"                border-radius: 10px;   /* 圆角 */\n"
"                background-color: transparent; /* 淡蓝色背景 */\n"
"            }")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 7, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.gridLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 800))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 821, 311))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_scripts = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_scripts.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_scripts.setObjectName("gridLayout_scripts")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 8)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("            QLabel {\n"
"                font-size: 9px;       /* 字体大小 */\n"
"                font-weight: bold;     /* 粗体 */\n"
"                padding: 10px;         /* 内边距 */\n"
"                border-radius: 10px;   /* 圆角 */\n"
"                background-color: transparent; /* 淡蓝色背景 */\n"
"            }")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("            QLabel {\n"
"                font-size: 9px;       /* 字体大小 */\n"
"                font-weight: bold;     /* 粗体 */\n"
"                padding: 10px;         /* 内边距 */\n"
"                border-radius: 10px;   /* 圆角 */\n"
"                background-color: transparent; /* 淡蓝色背景 */\n"
"            }")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("            QLabel {\n"
"                font-size: 9px;       /* 字体大小 */\n"
"                font-weight: bold;     /* 粗体 */\n"
"                padding: 10px;         /* 内边距 */\n"
"                border-radius: 10px;   /* 圆角 */\n"
"                background-color: transparent; /* 淡蓝色背景 */\n"
"            }")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("\n"
"    \n"
"            QLabel {\n"
"                font-size: 9px;       /* 字体大小 */\n"
"                font-weight: bold;     /* 粗体 */\n"
"                padding: 10px;         /* 内边距 */\n"
"                border-radius: 10px;   /* 圆角 */\n"
"                background-color: transparent; /* 淡蓝色背景 */\n"
"            }")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("            QLabel {\n"
"                font-size: 9px;       /* 字体大小 */\n"
"                font-weight: bold;     /* 粗体 */\n"
"                padding: 10px;         /* 内边距 */\n"
"                border-radius: 10px;   /* 圆角 */\n"
"                background-color: transparent; /* 淡蓝色背景 */\n"
"            }")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 3)
        self.label_welcome = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_welcome.sizePolicy().hasHeightForWidth())
        self.label_welcome.setSizePolicy(sizePolicy)
        self.label_welcome.setStyleSheet("\n"
"            QLabel {\n"
"                color: lightblue;           /* 文本颜色为蓝色 */\n"
"                font-style: italic;    /* 斜体 */\n"
"                font-size: 24px;       /* 字体大小 */\n"
"                font-weight: bold;     /* 粗体 */\n"
"                padding: 10px;         /* 内边距 */\n"
"                border-radius: 10px;   /* 圆角 */\n"
"                background-color: transparent; /* 淡蓝色背景 */\n"
"            }\n"
"")
        self.label_welcome.setObjectName("label_welcome")
        self.gridLayout.addWidget(self.label_welcome, 0, 0, 1, 8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Tool"))
        self.label_3.setText(_translate("Form", "ScriptName"))
        self.label_6.setText(_translate("Form", "Author"))
        self.label_4.setText(_translate("Form", "Version"))
        self.label_2.setText(_translate("Form", "NO"))
        self.label_5.setText(_translate("Form", "Description"))
        self.label_welcome.setText(_translate("Form", "CraftHub"))
